server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/badgemeal
    driver-class-name: org.mariadb.jdbc.Driver
    username: badgemeal
    password: badgemeal
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update